export enum OrderStatuses {
  CREATED = 'CREATED',
  PROCESSING = 'PROCESSING',
  PAYED = 'PAYED',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  RETURNED = 'RETURNED',
  CANCELED = 'CANCELED',
}
